### ISSUE TITLE
Add subvillains for Phoenix Five

### ISSUE THREAD

**Issue by RayosPL** [norsjensen/UnitedGenerator#2]
Phoenix Five in standalone mode works like this: Select one Villain, then add two other villains from Phoenix Five and slide them under, so only BAM effects are visible. Replace two main villain thread cards with two Phoenix Force thread cards

Already created PR, forgot to create issue first :D

**Comment by norsjensen** [comment]
I think that since you are already finding one villain card from Phoenix five, selecting two more at random would be very easy. So I do not think it is worth the complexity to include it in the generation.

**Comment by RayosPL** [comment]
Ok, I assumed that it would be a nice addition to already very good looking tool, but I will not insist ;)

**Comment by norsjensen** [comment]
No problem :-)
