### ISSUE TITLE
Villain starting location

### ISSUE THREAD

**Issue by RayosPL** [norsjensen/UnitedGenerator#3]
Some villains have pre-defined starting location. It would be nice to have some logic for that and show proper location on webpage.

Suggestion:
Add some logic to randomly select villain starting location (not be limited to first) and change styling for this location so it will be more visible at first glance

**Comment by norsjensen** [comment]
As the first location is already random (when allowed), I see no reason to also randomize the starting location on top of something random.

**Comment by RayosPL** [comment]
maybe, but I think adding a starting location field will be nice to have for those villains who have predefined starting location, and going from that it will be simple to add some styling/extra randomizer :) I'll create a PR in a minute, feel free to check it and if not needed you can close it

**Comment by norsjensen** [comment]
Sorry, but I do not think it is needed.
